name = "study-assist"
main = "src/index.js"
compatibility_date = "2024-01-01"
nodejs_compat = true

[build]
command = "npm run build"

# Development configuration
workers_dev = true

# Production configuration
routes = [
  { pattern = "study-llm.me", custom_domain = true }
]

# Configure CORS at the routing level
[[routes]]
pattern = "study-llm.me/cdn-cgi/speculation"
script = "functions/_middleware/speculation.js"

[site]
bucket = "./"

# 反馈 API Workers 配置
[[services]]
name = "feedback-api"
script = "workers/feedback-api.js"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "KV_FEEDBACK"
id = "your-kv-namespace-id"  # 替换为你的 KV 命名空间 ID
preview_id = "your-preview-kv-namespace-id"  # 预览环境的 KV 命名空间 ID

# 环境变量
[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://your-worker-domain.workers.dev"

# 开发环境配置
[env.development]
name = "study-assist-dev"
vars = { ENVIRONMENT = "development" }

# 生产环境配置  
[env.production]
name = "study-assist-prod"
vars = { ENVIRONMENT = "production" }

# 路由配置
[[routes]]
pattern = "your-domain.com/api/*"
zone_name = "your-domain.com"