# 反馈 API Workers 配置
name = "feedback-api"
main = "workers/feedback-api.js"
compatibility_date = "2024-01-01"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "KV_FEEDBACK"
id = "3a30f22f353e4ebf8a9e8f5cfa848df1"  # 替换为你的 KV 命名空间 ID
preview_id = "3a30f22f353e4ebf8a9e8f5cfa848df1"  # 预览环境的 KV 命名空间 ID

# 环境变量
[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://feedback-api.study-llm.me"

# 开发环境配置
[env.development]
name = "study-assist-dev"
vars = { ENVIRONMENT = "development" }

# 生产环境配置  
[env.production]
name = "study-assist-prod"
vars = { ENVIRONMENT = "production" }

# 路由配置
[[routes]]
pattern = "study-llm.me/api/*"
zone_name = "study-llm.me"

# 上传Worker配置
[[workers]]
name = "upload-worker"
main = "workers/upload-worker-fixed.js"
compatibility_date = "2024-01-01"

# D1数据库绑定
[[d1_databases]]
binding = "DB_GORE"
# 替换为实际的D1数据库ID
database_id = "8b1e14cd-d18f-493f-a51e-da7aceab06c7"
preview_database_id = "8b1e14cd-d18f-493f-a51e-da7aceab06c7"