name = "edge-tts"
main = "functions/api/worker-edge-tts.js"
compatibility_date = "2025-05-10"

[vars]
EDGE_TTS_TOKEN = "6A5AA1D4EAFF4E9FB37E23D68491D6F4"

[build]
command = "npm run build"

# Development configuration
workers_dev = true

# Production configuration
[[routes]]
pattern = "worker-edge-tts.study-llm.me"
custom_domain = true

# Security headers
[[rules]]
type = "HeaderRule"
zone_id = "*"
headers = [
  { name = "Access-Control-Allow-Origin", value = "*" },
  { name = "Access-Control-Allow-Methods", value = "GET, POST, OPTIONS" },
  { name = "Access-Control-Allow-Headers", value = "Content-Type, Authorization" },
  { name = "Access-Control-Max-Age", value = "86400" }
]
