# GLM Worker Configuration
name = "glm-worker"
main = "workers/glm-worker.js"
compatibility_date = "2024-01-01"

# Development environment
[env.development]
name = "glm-worker-dev"

# Production environment
[env.production]
name = "glm-worker-prod"

# Environment variables (set these using wrangler secret put)
# GLM_API_KEY = "your-glm-api-key-here"

# Routes configuration for custom domain
[[routes]]
pattern = "glm.study-llm.me/*"
zone_name = "study-llm.me"