compatibility_date = "2025-05-10"
nodejs_compat = true

[build]
command = "npm run build"

# Development configuration
workers_dev = true

# Production configuration

# Configure CORS at the routing level