# WS Feedback API Workers Configuration
name = "ws-feedback-api"
main = "workers/ws-feedback-worker.js"
compatibility_date = "2024-01-01"

# KV Namespace Binding
[[kv_namespaces]]
binding = "KV_WS_FEEDBACK"
id = "6ccff624a0bb47fa9fa025974fbbe435"  # KV namespace ID for WS feedback
preview_id = "6ccff624a0bb47fa9fa025974fbbe435"  # Preview environment KV namespace ID

# Environment Variables
[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://ws-feedback.study-llm.me"

# Development Environment Configuration
[env.development]
name = "ws-feedback-api-dev"
vars = { ENVIRONMENT = "development" }

# Production Environment Configuration  
[env.production]
name = "ws-feedback-api-prod"
vars = { ENVIRONMENT = "production" }

# Route Configuration
[[routes]]
pattern = "ws-feedback.study-llm.me/api/*"
zone_name = "study-llm.me"