# 故障 API Workers 配置
name = "fault-api"
main = "workers/fault-api-worker.js"
compatibility_date = "2024-01-01"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "KV_WS_HUB"
id = "3a30f22f353e4ebf8a9e8f5cfa848df1"  # 替换为你的 KV 命名空间 ID
preview_id = "3a30f22f353e4ebf8a9e8f5cfa848df1"  # 预览环境的 KV 命名空间 ID

# D1 数据库绑定
[[d1_databases]]
binding = "DB_WS_HUB"
database_name = "ws-hub-db"
database_id = "822ee467-e6d2-490e-9fdd-d78e8e526889"

# 环境变量
[vars]
ENVIRONMENT = "production"

# 开发环境配置
[env.development]
name = "fault-api-dev"
vars = { ENVIRONMENT = "development" }

# 生产环境配置  
[env.production]
name = "fault-api-prod"
vars = { ENVIRONMENT = "production" }

# 路由配置
[[routes]]
pattern = "study-llm.me/ws/api/*"
zone_name = "study-llm.me"