# GLM Worker Configuration
name = "glm-worker"
main = "workers/glm-worker.js"
compatibility_date = "2024-01-01"

# Development environment
[env.development]
name = "glm-worker-dev"

# Production environment
[env.production]
name = "glm-worker-prod"

# Environment variables
[env.production.vars]
GLM_API_KEY = "9fbf536a32af4fb6aa1f4747192cb038.dqpE1fqciLXyvuQg"

# Development environment variables
[env.development.vars]
GLM_API_KEY = "9fbf536a32af4fb6aa1f4747192cb038.dqpE1fqciLXyvuQg"

# KV Storage for async tasks
[[env.production.kv_namespaces]]
binding = "TASKS_KV"
id = "7fad284aa9f449d99b40e39b4eb249d9"

[[env.development.kv_namespaces]]
binding = "TASKS_KV"
id = "7fad284aa9f449d99b40e39b4eb249d9"

# Routes configuration for custom domain
[[routes]]
pattern = "glm.study-llm.me/*"
zone_name = "study-llm.me"