compatibility_date = "2025-05-10"
nodejs_compat = true

[build]
command = "npm run build"

# Development configuration
workers_dev = true

# Production configuration
routes = [
  { pattern = "study-llm.me", custom_domain = true }
]

# Configure CORS at the routing level
[[routes]]
pattern = "study-llm.me/cdn-cgi/speculation"
script = "functions/_middleware/speculation.js"

[site]
bucket = "./"