name = "study-assist-site"
compatibility_date = "2024-01-01"

# 静态站点配置
[site]
bucket = "./"
entry-point = "workers"

# 生产环境路由
[[routes]]
pattern = "study-llm.me/*"
zone_name = "study-llm.me"

# 开发环境配置
[env.development]
name = "study-assist-site-dev"

# 开发环境变量
[env.development.vars]
API_NINJAS_KEY = "2MR6hafEnZOt/iYufOp7Qw==dQRDzo5yZmxc2c7B"
WS_LOGIN_PWD = "12345"

# 生产环境配置  
[env.production]
name = "study-assist-site-prod"

# 生产环境变量
[env.production.vars]
API_NINJAS_KEY = "2MR6hafEnZOt/iYufOp7Qw==dQRDzo5yZmxc2c7B"
WS_LOGIN_PWD = "12345"