name = "edge-tts"
main = "functions/api/edge-tts.js"
compatibility_date = "2025-05-10"

[vars]
EDGE_TTS_API_KEY = "6A5AA1D4EAFF4E9FB37E23D68491D6F4"

[build]
command = "npm run build"

# Development configuration
workers_dev = true

# Production configuration
[[routes]]
pattern = "worker-edge-tts.study-llm.me"
custom_domain = true

# Configure CORS at the routing level
[[routes]]
pattern = "worker-edge-tts.study-llm.me"
custom_domain = true
cors = {
  allowed_origins = ["https://study-llm.me", "https://*.study-llm.me", "http://localhost:*"],
  allowed_methods = ["GET", "POST", "OPTIONS"],
  allowed_headers = ["Content-Type", "Authorization"],
  max_age = 86400
}
