[build]
command = "npm run build" # Adjust based on your build command
publish = "dist" # Adjust based on your output directory

[site]
bucket = "./dist" # Adjust based on your output directory

# Environment variables for all environments
[vars]
# Example: PUBLIC_API_URL = "https://api.example.com"
EDGE_TTS_TOKEN = "6A5AA1D4EAFF4E9FB37E23D68491D6F4"

# Functions configuration
[functions]
directory = "functions"
node_compat = true  # Enable Node.js compatibility

[[functions.routes]]
pattern = "/api/worker-edge-tts*"
module = "worker-edge-tts"

# Custom headers configuration
[[headers]]
for = "/*"
[headers.headers]
# Remove problematic Speculation-Rules header from base config
Speculation-Rules = ""
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

# CORS headers for Edge TTS API
[[headers]]
for = "/api/worker-edge-tts*"
[headers.headers]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Max-Age = "86400"

# Production environment variables
[env.production]
name = "production"
# Production-specific variables
[env.production.vars]
# Example: ENVIRONMENT = "production"

# Staging environment variables
[env.staging]
name = "staging"
# Staging-specific variables
[env.staging.vars]
# Example: ENVIRONMENT = "staging"

# Secrets are not stored in this file
# Use `wrangler secret put SECRET_NAME` to set secrets
# Or set them in the Cloudflare Dashboard
