name = "study-assist-site"
compatibility_date = "2024-01-01"

# 静态站点配置
[site]
bucket = "./"
entry-point = "workers"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "db_subjects"
database_id = "bf8b14ba-9c9a-4661-bee2-f53837449143"  # 替换为你的 D1 数据库 ID

[[d1_databases]]
binding = "DB_WS"
database_name = "ws-hub-db"
database_id = "822ee467-e6d2-490e-9fdd-d78e8e526889"  # 替换为你的 WS D1 数据库 ID

[[d1_databases]]
binding = "DB_GORE"
database_name = "db_gore"
database_id = "8b1e14cd-d18f-493f-a51e-da7aceab06c7"  # 替换为你的 GORE D1 数据库 ID

# 生产环境路由
[[routes]]
pattern = "study-llm.me/*"
zone_name = "study-llm.me"

# 开发环境配置
[env.development]
name = "study-assist-site-dev"

# 开发环境变量
[env.development.vars]
API_NINJAS_KEY = "2MR6hafEnZOt/iYufOp7Qw==dQRDzo5yZmxc2c7B"
WS_LOGIN_PWD = "12345"

# 生产环境配置  
[env.production]
name = "study-assist-site-prod"

# 生产环境变量
[env.production.vars]
API_NINJAS_KEY = "2MR6hafEnZOt/iYufOp7Qw==dQRDzo5yZmxc2c7B"
WS_LOGIN_PWD = "12345"