// Language translations
const translations = {
    zh: {
        // Common elements
        'login-title': '系统登录',
        'login-subtitle': '请输入您的凭据以访问系统',
        'username-label': '用户名',
        'password-label': '密码',
        'login-button': '登录',
        'guest-text': '访客身份访问',
        'login-error': '用户名或密码错误，请重试',
        'page-title': '戈尔设备故障管理',
        'nav-home': '首页',
        'nav-fault-list': '故障列表',
        'nav-new-fault': '新建故障',
        'nav-fault-stats': '故障统计',
        'nav-info-mgmt': '信息管理',
        'nav-logout': '退出登录',
        'card-fault-list-title': '故障列表',
        'card-fault-list-desc': '查看所有设备故障记录',
        'card-new-fault-title': '新建故障',
        'card-new-fault-desc': '添加新的设备故障记录',
        'card-fault-stats-title': '故障统计',
        'card-fault-stats-desc': '查看设备故障数据分析',
        'card-info-mgmt-title': '信息管理',
        'card-info-mgmt-desc': '管理设备与用户信息',
        'footer-text': '网页基于智谱大模型GLM-4.5创建',
        
        // Info Modal
        'info-modal-title': '关于戈尔设备故障管理系统',
        'info-modal-intro': '戈尔设备故障管理系统是一个专为设备维护和故障管理设计的综合性平台，旨在提高设备运行效率，减少停机时间，并优化维护资源分配。',
        'info-modal-main-purpose': '主要目的',
        'info-modal-purpose-desc': '本系统致力于为企业提供全面的设备故障管理解决方案，通过数字化手段实现故障记录、跟踪、分析和预防的全流程管理。',
        'info-modal-unique-features': '独特功能',
        'info-modal-feature-1': '<strong>故障全生命周期管理</strong>：从故障发现、记录、处理到解决的全过程跟踪',
        'info-modal-feature-2': '<strong>智能统计分析</strong>：提供多维度的故障数据分析，帮助识别故障模式和趋势',
        'info-modal-feature-3': '<strong>多角色权限管理</strong>：根据用户角色提供不同的功能访问权限',
        'info-modal-feature-4': '<strong>响应式设计</strong>：支持PC端和移动端访问，随时随地管理设备故障',
        'info-modal-feature-5': '<strong>玻璃态UI设计</strong>：采用现代玻璃态设计风格，提供优雅的用户体验',
        'info-modal-benefits': '系统优势',
        'info-modal-benefits-desc': '通过使用本系统，企业可以实现设备维护的数字化转型，提高故障响应速度，降低维护成本，延长设备使用寿命，最终提升整体运营效率。',
        
        // Fault List Page
        'fault-list-title': '故障列表',
        'fault-list-subtitle': '查看和管理所有设备故障记录',
        'filter-factory': '工厂筛选',
        'filter-equipment': '设备筛选',
        'filter-status': '状态筛选',
        'filter-urgency': '紧急程度筛选',
        'filter-apply': '应用筛选',
        'filter-reset': '重置筛选',
        'table-id': 'ID',
        'table-factory': '工厂',
        'table-equipment': '设备名称',
        'table-area': '区域',
        'table-subarea': '子区域',
        'table-fault-type': '故障类型',
        'table-fault-desc': '故障描述',
        'table-status': '状态',
        'table-urgency': '紧急程度',
        'table-reporter': '报告人',
        'table-report-time': '报告时间',
        'table-actions': '操作',
        'status-pending': '待处理',
        'status-in-progress': '处理中',
        'status-completed': '已完成',
        'urgency-low': '低',
        'urgency-medium': '中',
        'urgency-high': '高',
        'action-view': '查看',
        'action-edit': '编辑',
        'action-delete': '删除',
        'pagination-previous': '上一页',
        'pagination-next': '下一页',
        'pagination-info': '显示 {start}-{end} 条，共 {total} 条记录',
        'no-data': '暂无数据',
        
        // New Fault Page
        'new-fault-title': '新建故障',
        'new-fault-subtitle': '填写设备故障信息',
        'form-factory': '工厂',
        'form-equipment': '设备名称',
        'form-area': '区域',
        'form-subarea': '子区域',
        'form-fault-type': '故障类型',
        'form-fault-desc': '故障描述',
        'form-status': '状态',
        'form-urgency': '紧急程度',
        'form-reporter': '报告人',
        'form-report-time': '报告时间',
        'form-submit': '提交',
        'form-reset': '重置',
        'form-cancel': '取消',
        'form-save': '保存',
        'form-loading': '保存中...',
        'form-success': '故障记录保存成功',
        'form-error': '保存失败，请重试',
        
        // Fault Statistics Page
        'fault-stats-title': '故障统计',
        'fault-stats-subtitle': '设备故障数据分析',
        'stats-total': '故障总数',
        'stats-in-progress': '处理中',
        'stats-pending': '待处理',
        'stats-urgent': '紧急故障数',
        'chart-distribution': '按故障分类分布',
        'chart-trend': '故障时间趋势',
        'chart-equipment': '按设备分布',
        'chart-area': '按区域分布',
        'filter-month': '月',
        'filter-quarter': '季度',
        'filter-year': '年',
        'filter-equipment-btn': '按设备',
        'filter-area-btn': '按区域',
        'chart-fault-type': '故障分布',
        'chart-max': '最大值',
        'chart-min': '最小值',
        
        // Info Management Page
        'info-mgmt-title': '信息管理',
        'info-mgmt-subtitle': '管理设备与用户信息',
        'tab-equipment': '设备管理',
        'tab-user': '用户管理',
        'basic-data-maintenance': '基础数据维护',
        'fault-data-download': '故障数据下载',
        'download-description': '下载故障数据表格用于离线分析',
        'download-features': '功能特点：包含所有故障记录、支持Excel格式、可用于离线分析',
        'download-button': '下载故障数据',
        'action-add-single': '单次新增',
        'action-batch-download': '批量下载',
        'action-batch-upload': '批量上传',
        'modal-add-equipment': '新增设备',
        'modal-add-user': '新增用户',
        'modal-plant': '工厂',
        'modal-equipment-name': '设备名称',
        'modal-area': '区域',
        'modal-subarea': '子区域',
        'modal-name': '姓名',
        'modal-function': '部门',
        'modal-commitment': '岗位',
        'modal-save': '保存',
        'modal-cancel': '取消',
        'modal-loading': '保存中...',
        'modal-error': '保存失败: {error}',
        'modal-success-equipment': '设备添加成功!',
        'modal-success-user': '用户添加成功!',
        'modal-update-success-equipment': '设备更新成功!',
        'modal-update-success-user': '用户更新成功!',
        'modal-delete-confirm': '确定要删除这条记录吗？',
        'modal-delete-loading': '删除中...',
        'modal-delete-success': '删除成功',
        'modal-delete-error': '删除失败，请重试',
        'table-loading': '加载数据失败',
'load-data-error': '加载数据时发生错误',
        'upload-success': '上传成功! {message}',
        'upload-error': '上传失败: {message}',
        
        // Additional keys for fault-list.html
        'fault-detail-title': '故障详情',
        'fault-id-label': '故障ID',
        'description-section': '描述',
        'get-fault-detail-failed': '获取故障详情失败',
        'get-fault-detail-error': '获取故障详情时出错，请稍后重试',
        'process-fault-title': '处理故障',
        'status-label': '状态',
        'handler-label': '处理人',
        'handling-description-label': '处理说明',
        'resolution-label': '故障解决',
        'submit-button': '提交',
        'cancel-button': '取消',
        'fault-status-updated': '故障处理状态已更新',
        'update-failed': '更新失败',
        'unknown-error': '未知错误',
        'update-fault-status-error': '更新故障状态时出错，请稍后重试',
        'process-fault-error': '处理故障时出错，请稍后重试',
        'delete-fault-confirm': '确定要删除此故障记录吗？此操作不可撤销。',
        'fault-deleted': '故障记录已删除',
        'delete-failed': '删除失败',
        'delete-fault-error': '删除故障时出错，请稍后重试',
        'level-high': '高',
        'level-medium': '中',
        'level-low': '低',
        'level-urgent': '紧急',
        'status-pending': '待处理',
        'status-processing': '处理中',
        'status-resolved': '已解决',
        'status-completed': '已完成',
        'unknown-time': '未知时间',
        'no-matching-faults': '没有找到符合条件的故障记录',
        'load-column-width-error': '加载列宽时出错',
        
        // New Fault Page (new-fault.html)
        'new-fault-page-title': '新建故障',
        'new-fault-description': '添加新的设备故障记录',
        'new-fault-page-description': '添加新的设备故障记录',
        'form-required': '必填',
        'form-basic-info': '基本信息',
        'form-factory': '工厂',
        'form-fault-equipment': '故障设备',
        'form-fault-area': '故障区域',
        'form-fault-sub-area': '故障子区域',
        'form-fault-category': '故障分类',
        'form-fault-level': '故障等级',
        'form-report-time': '报告时间',
        'form-reporter': '报告人',
        'form-status': '状态',
        'form-select-status': '请选择状态',
        'form-status-pending': '待处理',
        'form-status-in-progress': '处理中',
        'form-status-resolved': '已解决',
        'form-fault-details': '故障详情',
        'form-fault-description': '故障描述',
        'form-ai-analysis': 'AI专业分析',
        'form-ai-analysis-title': 'AI专业分析与排查建议',
        'form-troubleshooting': '故障排查',
        'form-ai-troubleshoot': 'AI排查分析',
        'form-ai-troubleshoot-title': 'AI排查分析与解决方案',
        'form-root-cause': '故障根因',
        'form-resolution': '故障解决',
        'form-additional-info': '补充信息',
        'form-file-upload': '上传文件',
        'form-file-upload-hint': '支持上传多个文件，如图片、文档等',
        'form-submit': '提交',
        'form-cancel': '取消',
        'form-analyzing': '分析中...',
        'form-ai-professional-analysis': 'AI专业分析',
        'form-ai-troubleshooting-analysis': 'AI排查分析',
        'form-please-enter-fault-description': '请先输入故障描述',
        'form-please-enter-troubleshooting': '请先输入故障排查步骤',
        'form-ai-analysis-completed': 'AI专业分析与排查建议已完成',
        'form-ai-troubleshoot-completed': 'AI排查分析与解决方案已完成',
        'form-analysis-failed': '专业分析失败',
        'form-troubleshoot-failed': '排查分析失败',
        'form-analysis-error': '专业分析时出错，请稍后重试',
        'form-troubleshoot-error': '排查分析时出错，请稍后重试',
        'form-edit-fault-title': '编辑故障',
        'form-edit-fault-description': '编辑设备故障记录',
        'form-load-fault-data-failed': '加载故障数据失败',
        'form-load-fault-data-error': '加载故障数据失败，请稍后重试',
        'form-fault-updated-successfully': '故障信息已成功更新！',
        'form-fault-submitted-successfully': '故障报告已成功提交！',
        'form-submit-failed': '提交失败',
        'form-unknown-error': '未知错误',
        'form-submit-error': '提交故障报告时出错，请稍后重试',
        'form-cancel-confirm': '确定要取消吗？未保存的数据将丢失。',
        'form-select-plant': '请选择工厂',
        'form-select-equipment': '请选择设备',
        'form-select-area': '请选择区域',
        'form-select-sub-area': '请选择子区域',
        'form-select-reporter': '请选择报告人',
        'form-load-plant-data-failed': '加载工厂数据失败',
        'form-load-plant-data-error': '加载工厂数据时发生错误',
        'form-load-equipment-data-failed': '加载设备数据失败',
        'form-load-equipment-data-error': '加载设备数据时发生错误',
        'form-load-area-data-failed': '加载区域数据失败',
        'form-load-area-data-error': '加载区域数据时发生错误',
        'form-load-sub-area-data-failed': '加载子区域数据失败',
        'form-load-sub-area-data-error': '加载子区域数据时发生错误',
        'form-load-personnel-data-failed': '加载人员数据失败',
        'form-load-personnel-data-error': '加载人员数据时发生错误',
        
        // Additional keys for AI analysis functionality
        'error-analysis-error': '专业分析时出错，请稍后重试',
        'ai-professional-analysis': 'AI专业分析',
        'error-enter-fault-description': '请先输入故障描述',
        'error-enter-troubleshooting-steps': '请先输入故障排查步骤',
        'ai-analyzing': '分析中...',
        'error-cannot-get-analysis-result': '无法获取分析结果',
        'ai-troubleshooting-analysis-completed': 'AI排查分析与解决方案已完成',
        'error-troubleshooting-analysis-failed': '排查分析失败',
        'error-troubleshooting-analysis-error': '排查分析时出错，请稍后重试',
        'ai-troubleshooting-analysis': 'AI排查分析',
        // Fault List Page
        'fault-list-title': '故障列表',
        'fault-list-description': '查看和管理所有设备故障记录',
        'search-criteria': '搜索条件',
        'search-button': '搜索',
        'reset-button': '重置',
        'load-column-width-error': '加载列宽设置失败',
        'no-matching-faults': '没有找到匹配的故障记录',
        'view-button': '查看',
        'edit-button': '编辑',
        // Fault Detail Page
        'fault-detail-title': '故障详情',
        'fault-detail-description': '查看设备故障的详细信息',
        'basic-info': '基本信息',
        'fault-detail': '故障详情',
        'additional-info': '补充信息',
        'export-document': '导出文档',
        'fault-id': '故障ID',
        'plant': '工厂',
        'fault-equipment': '故障设备',
        'fault-area': '故障区域',
        'fault-subarea': '故障子区域',
        'fault-category': '故障分类',
        'fault-level': '故障等级',
        'report-time': '报告时间',
        'reporter': '报告人',
        'status': '状态',
        'fault-description': '故障描述',
        'troubleshooting': '故障排查',
        'root-cause': '故障根因',
        'resolution': '故障解决',
        'attachments': '附件信息',
        'export-fault-report': '导出故障报告',
        'export-description': '点击下方按钮将完整的故障信息（包括基本信息、故障详情、补充信息和附件）导出为Word文档。',
        'export-word-document': '导出为Word文档',
        'generating-document': '正在生成文档...',
        'back-to-list': '返回列表',
        'edit-fault': '编辑故障',
        'no-fault-id': '未指定故障ID',
        'load-fault-detail-failed': '加载故障详情失败',
        'no-attachments': '暂无附件',
        'equipment-fault-report': '设备故障报告',
        'fault-number': '故障编号',
        'processing-time': '处理时间',
        'resolution-time': '解决时间',
        'image-attachments': '图片附件',
        'other-attachments': '其他附件',
        'image-name': '图片名称',
        'file-size': '文件大小',
        'file-type': '文件类型',
        'image-link': '图片链接',
        'file-name': '文件名称',
        'file-link': '文件链接',
        'image-embed-error': '注意: 图片无法直接嵌入到文档中，请点击上方链接查看图片',
        'no-attachments-report': '此故障报告没有附件',
        'report-generation-info': '报告生成信息',
        'generation-time': '生成时间',
        'generation-method': '生成方式',
        'auto-generated': '系统自动生成',
        'export-failed': '导出失败',
        'export-success': '导出成功',
        'high': '高',
        'medium': '中',
        'low': '低',
        'unknown': '未知',
        'pending': '待处理',
        'processing': '处理中',
        'resolved': '已解决',
        'completed': '已完成',
        // Fault Statistics Page
        'fault-statistics-title': '故障统计',
        'fault-statistics-description': '查看设备故障数据分析与趋势',
        'total-faults': '故障总数',
        'in-progress': '处理中',
        'pending': '待处理',
        'urgent-faults': '紧急故障数',
        'fault-distribution': '故障分布',
        'fault-time-trend': '故障时间趋势',
        'fault-type-distribution': '故障类型分布',
        'fault-equipment-distribution': '故障设备分布',
        'fault-area-distribution': '故障区域分布',
        'monthly-statistics': '按月统计',
        'quarterly-statistics': '按季度统计',
        'yearly-statistics': '按年统计',
        'fault-type-chart-placeholder': '故障类型分布图表将显示在这里',
        'fault-trend-chart-placeholder': '故障时间趋势图表将显示在这里',
        'fetch-fault-data-failed': '获取故障数据失败',
        'fault-count': '故障数量',
        'maximum': '最大值',
        'minimum': '最小值',
        'fetch-fault-data-failed': '获取故障数据失败:',
        'equipment-distribution': '故障设备分布',
        'area-distribution': '故障区域分布',
        'fault-distribution': '故障分布',
        'fault-type': '故障类型',
        'month': '月',
        'quarter': '季度',
        'year': '年',
        'statistics-by-time-unit': '按{timeUnit}统计故障数量',
        'faults': '个故障',
        
        // Additional keys for fault-statistics.html
        'fault-stats-description': '查看设备故障数据分析与趋势',
        'stat-total-faults': '故障总数',
        'stat-processing': '处理中',
        'stat-pending': '待处理',
        'stat-urgent': '紧急故障数',
        'chart-distribution-title': '故障分布',
        'chart-trend-title': '故障时间趋势',
        'filter-category': '故障分类',
        'filter-plant': '工厂',
        'filter-equipment': '故障设备',
        'filter-area': '故障区域',
        'filter-level': '故障等级',
        'filter-reporter': '报告人',
        'filter-status': '状态',
        'filter-month': '按月统计',
        'filter-quarter': '按季度统计',
        'filter-year': '按年统计',
        'chart-distribution-placeholder': '故障类型分布图表将显示在这里',
        'chart-trend-placeholder': '故障时间趋势图表将显示在这里',
        
        // Additional keys for info-management.html
        'info-management-title': '信息管理',
        'info-management-description': '管理设备与用户信息',
        'basic-data-maintenance-title': '基础数据维护',
        'basic-data-maintenance-desc': '管理设备、用户和部门信息',
        'equipment-management': '设备管理',
        'user-management': '用户管理',
        'single-add': '单次新增',
        'batch-download': '批量下载',
        'batch-upload': '批量上传',
        'table-header-id': 'ID',
        'table-header-plant': '工厂',
        'table-header-equipment': '设备',
        'table-header-area': '区域',
        'table-header-subarea': '子区域',
        'table-header-name': '姓名',
        'table-header-department': '部门',
        'table-header-position': '岗位',
        'table-header-actions': '操作',
        'pagination-info': '显示 0-0 条，共 0 条记录',
        'pagination-prev': '上一页',
        'pagination-next': '下一页',
        'fault-data-download-title': '故障数据下载',
        'fault-data-download-desc': '下载所有故障数据到Excel文件',
        'download-info-text': '📊 下载包含所有故障记录的数据文件',
        'download-feature-1': '✅ 包含故障编号、设备名称、故障区域、故障等级等基础信息',
        'download-feature-2': '✅ 包含故障描述、排查步骤、根本原因、解决方案等详细信息',
        'download-feature-3': '✅ 不包含上传的附件文件',
        'download-fault-data-btn': '下载故障数据',
        'download-note': '文件格式：Excel (.xlsx)',
        'add-equipment-modal-title': '新增设备',
        'add-user-modal-title': '新增用户',
        'equipment-id-label': 'ID (自动生成)',
        'equipment-plant-label': '工厂',
        'equipment-name-label': '设备名称',
        'equipment-area-label': '区域',
        'equipment-subarea-label': '子区域',
        'user-id-label': 'ID (自动生成)',
        'user-plant-label': '工厂',
        'user-name-label': '姓名',
        'user-department-label': '部门',
        'user-position-label': '岗位',
        'save-btn': '保存',
        'cancel-btn': '取消',
        'save-error': '保存失败，请重试',
        'no-fault-data': '没有故障数据',
        'download-failed-prefix': '下载失败: ',
        'download-failed-network': '网络连接错误，请检查您的网络并重试',
        'download-failed-data': '获取数据失败，请稍后重试',
        'fetching-data': '正在获取数据...',
        'equipment-update-success': '设备更新成功!',
        'equipment-add-success': '设备添加成功!',
        'equipment-update-failed': '更新设备失败',
        'equipment-add-failed': '添加设备失败',
        'user-update-success': '用户更新成功!',
        'user-add-success': '用户添加成功!',
        'user-update-failed': '更新用户失败',
        'user-add-failed': '添加用户失败',
        'equipment-not-exist': '设备不存在',
        'user-not-exist': '用户不存在',
        'delete-success': '删除成功',
        'delete-failed': '删除失败',
        'delete-failed-retry': '删除失败，请重试',
        'delete-confirm': '确定要删除这条记录吗？',
        'delete-loading': '删除中...',
        'save-failed': '保存失败',
        'upload-success': '上传成功',
        'upload-failed': '上传失败',
        'delete-equipment-error': '删除设备出错',
        'delete-user-error': '删除用户出错',
        
        // Placeholder translations for new-fault.html
        'form-placeholder-equipment-name': '输入故障设备名称',
        'form-placeholder-fault-area': '输入故障区域',
        'form-placeholder-reporter': '输入报告人姓名',
        'form-placeholder-fault-description': '详细描述故障现象，应包括故障发生时间、地点、影响范围、故障症状、故障产生的条件、发生频率等',
        'form-placeholder-troubleshooting': '描述故障排查步骤，应包括检查故障现象、确认故障影响范围、记录排查过程和结果等',
        'form-placeholder-root-cause': '分析故障的根本原因，应包括故障发生的因果关系等',
        'form-placeholder-resolution': '描述故障解决方案，应包括修复故障的具体步骤、实际效果、预防措施（如日常点检、定期保养）等',
        'form-placeholder-additional-info': '输入其他补充信息',
        
        // Table headers for fault-list.html
        'table-header-status': '状态',
        'table-header-reporter': '报告人',
        'table-header-update-time': '更新时间',
        'table-header-report-time': '报告时间',
        'table-header-description': '故障描述',
        'table-header-level': '等级',
        'table-header-category': '分类',
        
        // Additional keys for fault-list.html
        'search-title': '搜索和筛选',
        'all-statuses': '所有状态',
        'all-levels': '所有级别',
        'all-plants': '所有工厂',
        'all-categories': '所有分类',
        'all-equipment': '所有设备',
        'all-areas': '所有区域',
        'all-subareas': '所有子区域',
        'all-reporters': '所有报告人',
        'filter-button': '筛选',
        'reset-button': '重置',
        'loading-faults': '正在加载故障数据...',
        'no-fault-data': '暂无故障数据',
        'table-header-update-time': '更新时间',
        'prev-page': '上一页',
        'next-page': '下一页'
    },
    en: {
        // Common elements
        'login-title': 'System Login',
        'login-subtitle': 'Please enter your credentials to login',
        'username-label': 'Username',
        'password-label': 'Password',
        'login-button': 'Login',
        'guest-text': 'Guest Access',
        'login-error': 'Username or password is incorrect, please try again',
        'page-title': 'Fault Management',
        'nav-home': 'Home',
        'nav-fault-list': 'Fault List',
        'nav-new-fault': 'New Fault',
        'nav-fault-stats': 'Fault Statistics',
        'nav-info-mgmt': 'Info Management',
        'nav-logout': 'Logout',
        'card-fault-list-title': 'Fault List',
        'card-fault-list-desc': 'View all equipment fault records',
        'card-new-fault-title': 'New Fault',
        'card-new-fault-desc': 'Add new equipment fault record',
        'card-fault-stats-title': 'Fault Statistics',
        'card-fault-stats-desc': 'View equipment fault data analysis',
        'card-info-mgmt-title': 'Info Management',
        'card-info-mgmt-desc': 'Manage equipment and user data',
        'footer-text': 'Site created with Zhipu\'s GLM-4.5 LLM',
        
        // Info Modal
        'info-modal-title': 'About Gore Equipment Fault Management System',
        'info-modal-intro': 'The Gore Equipment Fault Management System is a comprehensive platform designed specifically for equipment maintenance and fault management, aiming to improve equipment operational efficiency, reduce downtime, and optimize maintenance resource allocation.',
        'info-modal-main-purpose': 'Main Purpose',
        'info-modal-purpose-desc': 'This system is committed to providing enterprises with comprehensive equipment fault management solutions, achieving full-process management of fault recording, tracking, analysis, and prevention through digital means.',
        'info-modal-unique-features': 'Unique Features',
        'info-modal-feature-1': '<strong>Full Lifecycle Fault Management</strong>: Complete process tracking from fault discovery, recording, processing to resolution',
        'info-modal-feature-2': '<strong>Intelligent Statistical Analysis</strong>: Provides multi-dimensional fault data analysis to help identify fault patterns and trends',
        'info-modal-feature-3': '<strong>Multi-role Permission Management</strong>: Provides different functional access permissions based on user roles',
        'info-modal-feature-4': '<strong>Responsive Design</strong>: Supports PC and mobile access, manage equipment faults anytime, anywhere',
        'info-modal-feature-5': '<strong>Glassmorphism UI Design</strong>: Adopts modern glassmorphism design style to provide an elegant user experience',
        'info-modal-benefits': 'System Advantages',
        'info-modal-benefits-desc': 'By using this system, enterprises can achieve digital transformation of equipment maintenance, improve fault response speed, reduce maintenance costs, extend equipment service life, and ultimately enhance overall operational efficiency.',
        
        // Fault List Page
        'fault-list-title': 'Fault List',
        'fault-list-subtitle': 'View and manage all equipment fault records',
        'filter-factory': 'Factory Filter',
        'filter-equipment': 'Equipment Filter',
        'filter-status': 'Status Filter',
        'filter-urgency': 'Urgency Filter',
        'filter-apply': 'Apply Filters',
        'filter-reset': 'Reset Filters',
        'table-id': 'ID',
        'table-factory': 'Factory',
        'table-equipment': 'Equipment Name',
        'table-area': 'Area',
        'table-subarea': 'Sub Area',
        'table-fault-type': 'Fault Type',
        'table-fault-desc': 'Fault Description',
        'table-status': 'Status',
        'table-urgency': 'Urgency',
        'table-reporter': 'Reporter',
        'table-report-time': 'Report Time',
        'table-actions': 'Actions',
        'status-pending': 'Pending',
        'status-in-progress': 'In Progress',
        'status-completed': 'Completed',
        'urgency-low': 'Low',
        'urgency-medium': 'Medium',
        'urgency-high': 'High',
        'action-view': 'View',
        'action-edit': 'Edit',
        'action-delete': 'Delete',
        'pagination-previous': 'Previous',
        'pagination-next': 'Next',
        'pagination-info': 'Showing {start}-{end} of {total} records',
        'no-data': 'No data available',
        'view-button': 'View',
        'edit-button': 'Edit',

        // New Fault Page
        'new-fault-title': 'New Fault',
        'new-fault-subtitle': 'Fill in equipment fault information',
        'form-factory': 'Factory',
        'form-equipment': 'Equipment Name',
        'form-area': 'Area',
        'form-subarea': 'Sub Area',
        'form-fault-type': 'Fault Type',
        'form-fault-desc': 'Fault Description',
        'form-status': 'Status',
        'form-urgency': 'Urgency',
        'form-reporter': 'Reporter',
        'form-report-time': 'Report Time',
        'form-submit': 'Submit',
        'form-reset': 'Reset',
        'form-cancel': 'Cancel',
        'form-save': 'Save',
        'form-loading': 'Saving...',
        'form-success': 'Fault record saved successfully',
        'form-error': 'Save failed, please try again',
        
        // Fault Statistics Page
        'fault-stats-title': 'Fault Statistics',
        'fault-stats-subtitle': 'Equipment fault data analysis',
        'stats-total': 'Total Faults',
        'stats-in-progress': 'In Progress',
        'stats-pending': 'Pending',
        'stats-urgent': 'Urgent Faults',
        'chart-distribution': 'Distribution by Fault Type',
        'chart-trend': 'Fault Time Trend',
        'chart-equipment': 'Distribution by Equipment',
        'chart-area': 'Distribution by Area',
        'filter-month': 'Month',
        'filter-quarter': 'Quarter',
        'filter-year': 'Year',
        'filter-equipment-btn': 'By Equipment',
        'filter-area-btn': 'By Area',
        'chart-fault-type': 'Fault Distribution',
        'chart-max': 'Maximum',
        'chart-min': 'Minimum',
        
        // Info Management Page
        'info-mgmt-title': 'Info Management',
        'info-mgmt-subtitle': 'Manage equipment and user information',
        'tab-equipment': 'Equipment Management',
        'tab-user': 'User Management',
        'basic-data-maintenance': 'Basic Data Maintenance',
        'fault-data-download': 'Fault Data Download',
        'download-description': 'Download fault data table for offline analysis',
        'download-features': 'Features: Includes all fault records, supports Excel format, can be used for offline analysis',
        'download-button': 'Download Fault Data',
        'action-add-single': 'Add Single',
        'action-batch-download': 'Batch Download',
        'action-batch-upload': 'Batch Upload',
        'modal-add-equipment': 'Add Equipment',
        'modal-add-user': 'Add User',
        'modal-plant': 'Factory',
        'modal-equipment-name': 'Equipment Name',
        'modal-area': 'Area',
        'modal-subarea': 'Sub Area',
        'modal-name': 'Name',
        'modal-function': 'Department',
        'modal-commitment': 'Position',
        'modal-save': 'Save',
        'modal-cancel': 'Cancel',
        'modal-loading': 'Saving...',
        'modal-error': 'Save failed: {error}',
        'modal-success-equipment': 'Equipment added successfully!',
        'modal-success-user': 'User added successfully!',
        'modal-update-success-equipment': 'Equipment updated successfully!',
        'modal-update-success-user': 'User updated successfully!',
        'modal-delete-confirm': 'Are you sure you want to delete this record?',
        'modal-delete-loading': 'Deleting...',
        'modal-delete-success': 'Delete successful',
        'modal-delete-error': 'Delete failed, please try again',
        'table-loading': 'Failed to load data',
'load-data-error': 'Error occurred while loading data',
        'upload-success': 'Upload successful! {message}',
        'upload-error': 'Upload failed: {message}',
        
        // Additional keys for fault-list.html
        'fault-detail-title': 'Fault Detail',
        'fault-id-label': 'Fault ID',
        'description-section': 'Description',
        'get-fault-detail-failed': 'Failed to get fault detail',
        'get-fault-detail-error': 'Error getting fault detail, please try again later',
        'process-fault-title': 'Process Fault',
        'status-label': 'Status',
        'handler-label': 'Handler',
        'handling-description-label': 'Handling Description',
        'resolution-label': 'Fault Resolution',
        'submit-button': 'Submit',
        'cancel-button': 'Cancel',
        'fault-status-updated': 'Fault processing status has been updated',
        'update-failed': 'Update failed',
        'unknown-error': 'Unknown error',
        'update-fault-status-error': 'Error updating fault status, please try again later',
        'process-fault-error': 'Error processing fault, please try again later',
        'delete-fault-confirm': 'Are you sure you want to delete this fault record? This action cannot be undone.',
        'fault-deleted': 'Fault record has been deleted',
        'delete-failed': 'Delete failed',
        'delete-fault-error': 'Error deleting fault, please try again later',
        'level-high': 'High',
        'level-medium': 'Medium',
        'level-low': 'Low',
        'level-urgent': 'Urgent',
        'status-pending': 'Pending',
        'status-processing': 'Processing',
        'status-resolved': 'Resolved',
        'status-completed': 'Completed',
        'unknown-time': 'Unknown time',
        'no-matching-faults': 'No matching fault records found',
        'load-column-width-error': 'Error loading column width',
        
        // New Fault Page (new-fault.html)
        'new-fault-page-title': 'New Fault',
        'new-fault-description': 'Add new equipment fault record',
        'new-fault-page-description': 'Add new equipment fault record',
        'form-required': 'Required',
        'form-basic-info': 'Basic Information',
        'form-factory': 'Factory',
        'form-fault-equipment': 'Fault Equipment',
        'form-fault-area': 'Fault Area',
        'form-fault-sub-area': 'Fault Sub Area',
        'form-fault-category': 'Fault Category',
        'form-fault-level': 'Fault Level',
        'form-report-time': 'Report Time',
        'form-reporter': 'Reporter',
        'form-status': 'Status',
        'form-select-status': 'Select Status',
        'form-status-pending': 'Pending',
        'form-status-in-progress': 'In Progress',
        'form-status-resolved': 'Resolved',
        'form-fault-details': 'Fault Details',
        'form-fault-description': 'Fault Description',
        'form-ai-analysis': 'AI Professional Analysis',
        'form-ai-analysis-title': 'AI Professional Analysis and Troubleshooting Suggestions',
        'form-troubleshooting': 'Fault Troubleshooting',
        'form-ai-troubleshoot': 'AI Troubleshooting Analysis',
        'form-ai-troubleshoot-title': 'AI Troubleshooting Analysis and Solutions',
        'form-root-cause': 'Root Cause',
        'form-resolution': 'Fault Resolution',
        'form-additional-info': 'Additional Information',
        'form-file-upload': 'Upload Files',
        'form-file-upload-hint': 'Support uploading multiple files, such as images, documents, etc.',
        'form-submit': 'Submit',
        'form-cancel': 'Cancel',
        'form-analyzing': 'Analyzing...',
        'form-ai-professional-analysis': 'AI Professional Analysis',
        'form-ai-troubleshooting-analysis': 'AI Troubleshooting Analysis',
        'form-please-enter-fault-description': 'Please enter fault description first',
        'form-please-enter-troubleshooting': 'Please enter troubleshooting steps first',
        'form-ai-analysis-completed': 'AI professional analysis and troubleshooting suggestions completed',
        'form-ai-troubleshoot-completed': 'AI troubleshooting analysis and solutions completed',
        'form-analysis-failed': 'Professional analysis failed',
        'form-troubleshoot-failed': 'Troubleshooting analysis failed',
        'form-analysis-error': 'Error during professional analysis, please try again later',
        'form-troubleshoot-error': 'Error during troubleshooting analysis, please try again later',
        'form-edit-fault-title': 'Edit Fault',
        'form-edit-fault-description': 'Edit equipment fault record',
        'form-load-fault-data-failed': 'Failed to load fault data',
        'form-load-fault-data-error': 'Failed to load fault data, please try again later',
        'form-fault-updated-successfully': 'Fault information has been successfully updated!',
        'form-fault-submitted-successfully': 'Fault report has been successfully submitted!',
        'form-submit-failed': 'Submission failed',
        'form-unknown-error': 'Unknown error',
        'form-submit-error': 'Error submitting fault report, please try again later',
        'form-cancel-confirm': 'Are you sure you want to cancel? Unsaved data will be lost.',
        'form-select-plant': 'Please select a factory',
        'form-select-equipment': 'Please select equipment',
        'form-select-area': 'Please select an area',
        'form-select-sub-area': 'Please select a sub area',
        'form-select-reporter': 'Please select a reporter',
        'form-load-plant-data-failed': 'Failed to load factory data',
        'form-load-plant-data-error': 'Error occurred while loading factory data',
        'form-load-equipment-data-failed': 'Failed to load equipment data',
        'form-load-equipment-data-error': 'Error occurred while loading equipment data',
        'form-load-area-data-failed': 'Failed to load area data',
        'form-load-area-data-error': 'Error occurred while loading area data',
        'form-load-sub-area-data-failed': 'Failed to load sub area data',
        'form-load-sub-area-data-error': 'Error occurred while loading sub area data',
        'form-load-personnel-data-failed': 'Failed to load personnel data',
        'form-load-personnel-data-error': 'Error occurred while loading personnel data',
        
        // Additional keys for AI analysis functionality
        'error-analysis-error': 'Error during professional analysis, please try again later',
        'ai-professional-analysis': 'AI Professional Analysis',
        'error-enter-fault-description': 'Please enter fault description first',
        'error-enter-troubleshooting-steps': 'Please enter troubleshooting steps first',
        'ai-analyzing': 'Analyzing...',
        'error-cannot-get-analysis-result': 'Cannot get analysis result',
        'ai-troubleshooting-analysis-completed': 'AI troubleshooting analysis and solutions completed',
        'error-troubleshooting-analysis-failed': 'Troubleshooting analysis failed',
        'error-troubleshooting-analysis-error': 'Error during troubleshooting analysis, please try again later',
        'ai-troubleshooting-analysis': 'AI Troubleshooting Analysis',
        // Fault List Page
        'fault-list-title': 'Fault List',
        'fault-list-description': 'View and manage all equipment fault records',
        'search-criteria': 'Search Criteria',
        'search-button': 'Search',
        'reset-button': 'Reset',
        'load-column-width-error': 'Failed to load column width settings',
        'no-matching-faults': 'No matching fault records found',
        // Fault Detail Page
        'fault-detail-title': 'Fault Detail',
        'fault-detail-description': 'View detailed information of equipment fault',
        'basic-info': 'Basic Information',
        'fault-detail': 'Fault Detail',
        'additional-info': 'Additional Information',
        'export-document': 'Export Document',
        'fault-id': 'Fault ID',
        'plant': 'Factory',
        'fault-equipment': 'Fault Equipment',
        'fault-area': 'Fault Area',
        'fault-subarea': 'Fault Sub Area',
        'fault-category': 'Fault Category',
        'fault-level': 'Fault Level',
        'report-time': 'Report Time',
        'reporter': 'Reporter',
        'status': 'Status',
        'fault-description': 'Fault Description',
        'troubleshooting': 'Fault Troubleshooting',
        'root-cause': 'Root Cause',
        'resolution': 'Fault Resolution',
        'attachments': 'Attachment Information',
        'export-fault-report': 'Export Fault Report',
        'export-description': 'Click the button below to export the complete fault information (including basic information, fault details, additional information and attachments) as a Word document.',
        'export-word-document': 'Export as Word Document',
        'generating-document': 'Generating document...',
        'back-to-list': 'Back to List',
        'edit-fault': 'Edit Fault',
        'no-fault-id': 'No fault ID specified',
        'load-fault-detail-failed': 'Failed to load fault detail',
        'no-attachments': 'No attachments',
        'equipment-fault-report': 'Equipment Fault Report',
        'fault-number': 'Fault Number',
        'processing-time': 'Processing Time',
        'resolution-time': 'Resolution Time',
        'image-attachments': 'Image Attachments',
        'other-attachments': 'Other Attachments',
        'image-name': 'Image Name',
        'file-size': 'File Size',
        'file-type': 'File Type',
        'image-link': 'Image Link',
        'file-name': 'File Name',
        'file-link': 'File Link',
        'image-embed-error': 'Note: Images cannot be directly embedded in the document, please click the link above to view images',
        'no-attachments-report': 'This fault report has no attachments',
        'report-generation-info': 'Report Generation Information',
        'generation-time': 'Generation Time',
        'generation-method': 'Generation Method',
        'auto-generated': 'System Automatically Generated',
        'export-failed': 'Export failed',
        'export-success': 'Export successful',
        'high': 'High',
        'medium': 'Medium',
        'low': 'Low',
        'unknown': 'Unknown',
        'pending': 'Pending',
        'processing': 'Processing',
        'resolved': 'Resolved',
        'completed': 'Completed',
        // Fault Statistics Page
        'fault-statistics-title': 'Fault Statistics',
        'fault-statistics-description': 'View equipment fault data analysis and trends',
        'total-faults': 'Total Faults',
        'in-progress': 'In Progress',
        'pending': 'Pending',
        'urgent-faults': 'Urgent Faults',
        'fault-distribution': 'Fault Distribution',
        'fault-time-trend': 'Fault Time Trend',
        'fault-type-distribution': 'Fault Type Distribution',
        'fault-equipment-distribution': 'Fault Equipment Distribution',
        'fault-area-distribution': 'Fault Area Distribution',
        'monthly-statistics': 'Monthly Statistics',
        'quarterly-statistics': 'Quarterly Statistics',
        'yearly-statistics': 'Yearly Statistics',
        'fault-type-chart-placeholder': 'Fault type distribution chart will be displayed here',
        'fault-trend-chart-placeholder': 'Fault time trend chart will be displayed here',
        'fetch-fault-data-failed': 'Failed to fetch fault data',
        'fault-count': 'Fault Count',
        'maximum': 'Maximum',
        'minimum': 'Minimum',
        'fetch-fault-data-failed': 'Failed to fetch fault data:',
        'equipment-distribution': 'Equipment Distribution',
        'area-distribution': 'Area Distribution',
        'fault-distribution': 'Fault Distribution',
        'fault-type': 'Fault Type',
        'month': 'Month',
        'quarter': 'Quarter',
        'year': 'Year',
        'statistics-by-time-unit': 'Fault Count by {timeUnit}',
        'faults': 'faults',
        
        // Additional keys for fault-statistics.html
        'fault-stats-description': 'View equipment fault data analysis and trends',
        'stat-total-faults': 'Total Faults',
        'stat-processing': 'Processing',
        'stat-pending': 'Pending',
        'stat-urgent': 'Urgent Faults',
        'chart-distribution-title': 'Fault Distribution',
        'chart-trend-title': 'Fault Time Trend',
        'filter-category': 'Fault Category',
        'filter-plant': 'Plant',
        'filter-equipment': 'Fault Equipment',
        'filter-area': 'Fault Area',
        'filter-level': 'Fault Level',
        'filter-reporter': 'Reporter',
        'filter-status': 'Status',
        'filter-month': 'Monthly Statistics',
        'filter-quarter': 'Quarterly Statistics',
        'filter-year': 'Yearly Statistics',
        'chart-distribution-placeholder': 'Fault type distribution chart will be displayed here',
        'chart-trend-placeholder': 'Fault time trend chart will be displayed here',
        
        // Additional keys for info-management.html
        'info-management-title': 'Data Management',
        'info-management-description': 'Manage equipment and user data',
        'basic-data-maintenance-title': 'Basic Data Maintenance',
        'basic-data-maintenance-desc': 'Manage equipment and user data',
        'equipment-management': 'Equipment Data',
        'user-management': 'User Data',
        'single-add': 'Single Add',
        'batch-download': 'Batch Download',
        'batch-upload': 'Batch Upload',
        'table-header-id': 'ID',
        'table-header-plant': 'Plant',
        'table-header-equipment': 'Equipment',
        'table-header-area': 'Area',
        'table-header-subarea': 'Sub-area',
        'table-header-name': 'Name',
        'table-header-department': 'Department',
        'table-header-position': 'Position',
        'table-header-actions': 'Actions',
        'pagination-info': 'Showing 0-0 of 0 records',
        'pagination-prev': 'Previous',
        'pagination-next': 'Next',
        'fault-data-download-title': 'Fault Data Download',
        'fault-data-download-desc': 'Download all fault data to Excel file',
        'download-info-text': '📊 Download data file containing all fault records',
        'download-feature-1': '✅ Includes basic information such as fault ID, equipment name, fault area, fault level',
        'download-feature-2': '✅ Includes detailed information such as fault description, troubleshooting steps, root cause, solution',
        'download-feature-3': '✅ Does not include uploaded attachment files',
        'download-fault-data-btn': 'Download Fault Data',
        'download-note': 'File format: Excel (.xlsx)',
        'add-equipment-modal-title': 'Add Equipment',
        'add-user-modal-title': 'Add User',
        'equipment-id-label': 'ID (Auto-generated)',
        'equipment-plant-label': 'Plant',
        'equipment-name-label': 'Equipment Name',
        'equipment-area-label': 'Area',
        'equipment-subarea-label': 'Sub-area',
        'user-id-label': 'ID (Auto-generated)',
        'user-plant-label': 'Plant',
        'user-name-label': 'Name',
        'user-department-label': 'Department',
        'user-position-label': 'Position',
        'save-btn': 'Save',
        'cancel-btn': 'Cancel',
        'save-error': 'Save failed, please try again',
        'no-fault-data': 'No fault data',
        'download-failed-prefix': 'Download failed: ',
        'download-failed-network': 'Network connection error, please check your network and try again',
        'download-failed-data': 'Failed to get data, please try again later',
        'fetching-data': 'Fetching data...',
        'equipment-update-success': 'Equipment updated successfully!',
        'equipment-add-success': 'Equipment added successfully!',
        'equipment-update-failed': 'Failed to update equipment',
        'equipment-add-failed': 'Failed to add equipment',
        'user-update-success': 'User updated successfully!',
        'user-add-success': 'User added successfully!',
        'user-update-failed': 'Failed to update user',
        'user-add-failed': 'Failed to add user',
        'equipment-not-exist': 'Equipment does not exist',
        'user-not-exist': 'User does not exist',
        'delete-success': 'Delete successful',
        'delete-failed': 'Delete failed',
        'delete-failed-retry': 'Delete failed, please try again',
        'delete-confirm': 'Are you sure you want to delete this record?',
        'delete-loading': 'Deleting...',
        'save-failed': 'Save failed',
        'upload-success': 'Upload successful',
        'upload-failed': 'Upload failed',
        'delete-equipment-error': 'Delete equipment error',
        'delete-user-error': 'Delete user error',
        
        // Placeholder translations for new-fault.html
        'form-placeholder-equipment-name': 'Enter fault equipment name',
        'form-placeholder-fault-area': 'Enter fault area',
        'form-placeholder-reporter': 'Enter reporter name',
        'form-placeholder-fault-description': 'Describe the fault phenomenon in detail, including fault occurrence time, location, impact range, fault symptoms, conditions for fault occurrence, frequency, etc.',
        'form-placeholder-troubleshooting': 'Describe the troubleshooting steps, including checking fault phenomena, confirming the impact range, recording the troubleshooting process and results, etc.',
        'form-placeholder-root-cause': 'Analyze the root cause of the fault, including the causal relationship of the fault occurrence, etc.',
        'form-placeholder-resolution': 'Describe the fault solution, including specific steps to fix the fault, actual effects, preventive measures (such as daily inspections, regular maintenance), etc.',
        'form-placeholder-additional-info': 'Enter other additional information',
        
        // Table headers for fault-list.html
        'table-header-status': 'Status',
        'table-header-reporter': 'Reporter',
        'table-header-update-time': 'Update Time',
        'table-header-report-time': 'Report Time',
        'table-header-description': 'Description',
        'table-header-level': 'Level',
        'table-header-category': 'Category',
        
        // Additional keys for fault-list.html
        'search-title': 'Search and Filter',
        'all-statuses': 'All Statuses',
        'all-levels': 'All Levels',
        'all-plants': 'All Plants',
        'all-categories': 'All Categories',
        'all-equipment': 'All Equipment',
        'all-areas': 'All Areas',
        'all-subareas': 'All Subareas',
        'all-reporters': 'All Reporters',
        'filter-button': 'Filter',
        'reset-button': 'Reset',
        'loading-faults': 'Loading fault data...',
        'no-fault-data': 'No fault data',
        'table-header-update-time': 'Update Time',
        'prev-page': 'Previous',
        'next-page': 'Next',
        
        // Fault Detail Page
        'tab-basic-info': 'Basic Info',
        'tab-fault-detail': 'Fault Detail',
        'tab-attachments': 'Additional Info',
        'tab-export': 'Export Document',
        'basic-info-title': 'Basic Information',
        'fault-id-label': 'Fault ID',
        'plant-label': 'Plant',
        'equipment-label': 'Fault Equipment',
        'area-label': 'Fault Area',
        'subarea-label': 'Fault Subarea',
        'category-label': 'Fault Category',
        'level-label': 'Fault Level',
        'report-time-label': 'Report Time',
        'reporter-label': 'Reporter',
        'status-label': 'Status',
        'fault-description-title': 'Fault Description',
        'fault-troubleshooting-title': 'Fault Troubleshooting',
        'fault-root-cause-title': 'Fault Root Cause',
        'fault-resolution-title': 'Fault Resolution',
        'additional-info-title': 'Additional Information',
        'attachments-title': 'Attachment Information',
        'export-report-title': 'Export Fault Report',
        'export-report-description': 'Click the button below to export the complete fault information (including basic information, fault details, additional information and attachments) as a Word document.',
        'export-word-btn': 'Export as Word Document',
        'back-to-list-btn': 'Back to List',
        'edit-fault-btn': 'Edit Fault',
        'no-fault-id-specified': 'No fault ID specified',
        'load-fault-detail-error': 'Failed to load fault detail',
        'no-attachments': 'No attachments',
        'size-bytes': 'Bytes',
        'size-kb': 'KB',
        'size-mb': 'MB',
        'size-gb': 'GB',
        'generating-document': 'Generating document...',
        'image-embed-error': 'Note: Images cannot be directly embedded in the document, please click the link above to view images',
        'file-name': 'File Name',
        'file-size': 'File Size',
        'file-type': 'File Type',
        'image-name': 'Image Name',
        'image-link': 'Image Link',
        'file-link': 'File Link',
        'image-attachments': 'Image Attachments',
        'other-attachments': 'Other Attachments',
        'report-generation-info': 'Report Generation Information',
        'generation-time': 'Generation Time',
        'generation-method': 'Generation Method',
        'auto-generated': 'Automatically generated by system',
        'level-high': 'High',
        'level-medium': 'Medium',
        'level-low': 'Low',
        'level-unknown': 'Unknown',
        'status-pending': 'Pending',
        'status-processing': 'Processing',
        'status-resolved': 'Resolved',
        'status-completed': 'Completed',
        'status-unknown': 'Unknown'
    },
};

// Current language
let currentLanguage = 'zh';

// Function to set the language
function setLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('language', lang);
    updatePageLanguage();
}

// Function to update the page language
function updatePageLanguage() {
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            element.textContent = translations[currentLanguage][key];
        }
    });
    
    // Update title tags
    document.querySelectorAll('title[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            element.textContent = translations[currentLanguage][key];
        }
    });
    
    // Update placeholders
    document.querySelectorAll('[data-lang-placeholder]').forEach(element => {
        const key = element.getAttribute('data-lang-placeholder');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            element.placeholder = translations[currentLanguage][key];
        }
    });
    
    // Update title attributes
    document.querySelectorAll('[data-lang_title]').forEach(element => {
        const key = element.getAttribute('data-lang_title');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            element.title = translations[currentLanguage][key];
        }
    });
}

// Initialize language from localStorage or browser language
function initializeLanguage() {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && translations[savedLanguage]) {
        currentLanguage = savedLanguage;
    } else {
        // Try to detect browser language
        const browserLang = navigator.language.split('-')[0];
        if (translations[browserLang]) {
            currentLanguage = browserLang;
        }
    }
    updatePageLanguage();
}

// Function to get translation text
function getTranslation(key) {
    return translations[currentLanguage][key] || key;
}

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', initializeLanguage);