// Language translations
const translations = {
    zh: {
        // Common elements
        'login-title': '系统登录',
        'login-subtitle': '请输入您的凭据以访问系统',
        'username-label': '用户名',
        'password-label': '密码',
        'login-button': '登录',
        'guest-text': '访客身份访问',
        'login-error': '用户名或密码错误，请重试',
        'page-title': '戈尔设备故障管理',
        'nav-home': '首页',
        'nav-fault-list': '故障列表',
        'nav-new-fault': '新建故障',
        'nav-fault-stats': '故障统计',
        'nav-info-mgmt': '信息管理',
        'nav-logout': '退出登录',
        'card-fault-list-title': '故障列表',
        'card-fault-list-desc': '查看所有设备故障记录',
        'card-new-fault-title': '新建故障',
        'card-new-fault-desc': '添加新的设备故障记录',
        'card-fault-stats-title': '故障统计',
        'card-fault-stats-desc': '查看设备故障数据分析',
        'card-info-mgmt-title': '信息管理',
        'card-info-mgmt-desc': '管理设备与用户信息',
        'footer-text': '网页基于智谱大模型GLM-4.5创建',
        
        // Fault List Page
        'fault-list-title': '故障列表',
        'fault-list-subtitle': '查看和管理所有设备故障记录',
        'filter-factory': '工厂筛选',
        'filter-equipment': '设备筛选',
        'filter-status': '状态筛选',
        'filter-urgency': '紧急程度筛选',
        'filter-apply': '应用筛选',
        'filter-reset': '重置筛选',
        'table-id': 'ID',
        'table-factory': '工厂',
        'table-equipment': '设备名称',
        'table-area': '区域',
        'table-subarea': '子区域',
        'table-fault-type': '故障类型',
        'table-fault-desc': '故障描述',
        'table-status': '状态',
        'table-urgency': '紧急程度',
        'table-reporter': '报告人',
        'table-report-time': '报告时间',
        'table-actions': '操作',
        'status-pending': '待处理',
        'status-in-progress': '处理中',
        'status-completed': '已完成',
        'urgency-low': '低',
        'urgency-medium': '中',
        'urgency-high': '高',
        'action-view': '查看',
        'action-edit': '编辑',
        'action-delete': '删除',
        'pagination-previous': '上一页',
        'pagination-next': '下一页',
        'pagination-info': '显示 {start}-{end} 条，共 {total} 条记录',
        'no-data': '暂无数据',
        
        // New Fault Page
        'new-fault-title': '新建故障',
        'new-fault-subtitle': '填写设备故障信息',
        'form-factory': '工厂',
        'form-equipment': '设备名称',
        'form-area': '区域',
        'form-subarea': '子区域',
        'form-fault-type': '故障类型',
        'form-fault-desc': '故障描述',
        'form-status': '状态',
        'form-urgency': '紧急程度',
        'form-reporter': '报告人',
        'form-report-time': '报告时间',
        'form-submit': '提交',
        'form-reset': '重置',
        'form-cancel': '取消',
        'form-save': '保存',
        'form-loading': '保存中...',
        'form-success': '故障记录保存成功',
        'form-error': '保存失败，请重试',
        
        // Fault Statistics Page
        'fault-stats-title': '故障统计',
        'fault-stats-subtitle': '设备故障数据分析',
        'stats-total': '故障总数',
        'stats-in-progress': '处理中',
        'stats-pending': '待处理',
        'stats-urgent': '紧急故障数',
        'chart-distribution': '按故障分类分布',
        'chart-trend': '故障时间趋势',
        'chart-equipment': '按设备分布',
        'chart-area': '按区域分布',
        'filter-month': '月',
        'filter-quarter': '季度',
        'filter-year': '年',
        'filter-equipment-btn': '按设备',
        'filter-area-btn': '按区域',
        'chart-fault-type': '故障分布',
        'chart-max': '最大值',
        'chart-min': '最小值',
        
        // Info Management Page
        'info-mgmt-title': '信息管理',
        'info-mgmt-subtitle': '管理设备与用户信息',
        'tab-equipment': '设备管理',
        'tab-user': '用户管理',
        'basic-data-maintenance': '基础数据维护',
        'fault-data-download': '故障数据下载',
        'download-description': '下载故障数据表格用于离线分析',
        'download-features': '功能特点：包含所有故障记录、支持Excel格式、可用于离线分析',
        'download-button': '下载故障数据',
        'action-add-single': '单次新增',
        'action-batch-download': '批量下载',
        'action-batch-upload': '批量上传',
        'modal-add-equipment': '新增设备',
        'modal-add-user': '新增用户',
        'modal-plant': '工厂',
        'modal-equipment-name': '设备名称',
        'modal-area': '区域',
        'modal-subarea': '子区域',
        'modal-name': '姓名',
        'modal-function': '部门',
        'modal-commitment': '岗位',
        'modal-save': '保存',
        'modal-cancel': '取消',
        'modal-loading': '保存中...',
        'modal-error': '保存失败: {error}',
        'modal-success-equipment': '设备添加成功!',
        'modal-success-user': '用户添加成功!',
        'modal-update-success-equipment': '设备更新成功!',
        'modal-update-success-user': '用户更新成功!',
        'modal-delete-confirm': '确定要删除这条记录吗？',
        'modal-delete-loading': '删除中...',
        'modal-delete-success': '删除成功',
        'modal-delete-error': '删除失败，请重试',
        'table-loading': '加载数据失败',
        'upload-success': '上传成功! {message}',
        'upload-error': '上传失败: {message}',
        
        // Additional keys for fault-list.html
        'fault-detail-title': '故障详情',
        'fault-id-label': '故障ID',
        'description-section': '描述',
        'get-fault-detail-failed': '获取故障详情失败',
        'get-fault-detail-error': '获取故障详情时出错，请稍后重试',
        'process-fault-title': '处理故障',
        'status-label': '状态',
        'handler-label': '处理人',
        'handling-description-label': '处理说明',
        'resolution-label': '故障解决',
        'submit-button': '提交',
        'cancel-button': '取消',
        'fault-status-updated': '故障处理状态已更新',
        'update-failed': '更新失败',
        'unknown-error': '未知错误',
        'update-fault-status-error': '更新故障状态时出错，请稍后重试',
        'process-fault-error': '处理故障时出错，请稍后重试',
        'delete-fault-confirm': '确定要删除此故障记录吗？此操作不可撤销。',
        'fault-deleted': '故障记录已删除',
        'delete-failed': '删除失败',
        'delete-fault-error': '删除故障时出错，请稍后重试',
        'level-high': '高',
        'level-medium': '中',
        'level-low': '低',
        'level-urgent': '紧急',
        'status-pending': '待处理',
        'status-processing': '处理中',
        'status-resolved': '已解决',
        'status-completed': '已完成',
        'unknown-time': '未知时间',
        'no-matching-faults': '没有找到符合条件的故障记录',
        'load-column-width-error': '加载列宽时出错',
        
        // New Fault Page (new-fault.html)
        'new-fault-page-title': '新建故障',
        'new-fault-page-description': '添加新的设备故障记录',
        'form-required': '必填',
        'form-basic-info': '基本信息',
        'form-factory': '工厂',
        'form-fault-equipment': '故障设备',
        'form-fault-area': '故障区域',
        'form-fault-sub-area': '故障子区域',
        'form-fault-category': '故障分类',
        'form-fault-level': '故障等级',
        'form-report-time': '报告时间',
        'form-reporter': '报告人',
        'form-status': '状态',
        'form-select-status': '请选择状态',
        'form-status-pending': '待处理',
        'form-status-in-progress': '处理中',
        'form-status-resolved': '已解决',
        'form-fault-details': '故障详情',
        'form-fault-description': '故障描述',
        'form-ai-analysis': 'AI专业分析',
        'form-ai-analysis-title': 'AI专业分析与排查建议',
        'form-troubleshooting': '故障排查',
        'form-ai-troubleshoot': 'AI排查分析',
        'form-ai-troubleshoot-title': 'AI排查分析与解决方案',
        'form-root-cause': '故障根因',
        'form-resolution': '故障解决',
        'form-additional-info': '补充信息',
        'form-file-upload': '上传文件',
        'form-file-upload-hint': '支持上传多个文件，如图片、文档等',
        'form-submit': '提交',
        'form-cancel': '取消',
        'form-analyzing': '分析中...',
        'form-ai-professional-analysis': 'AI专业分析',
        'form-ai-troubleshooting-analysis': 'AI排查分析',
        'form-please-enter-fault-description': '请先输入故障描述',
        'form-please-enter-troubleshooting': '请先输入故障排查步骤',
        'form-ai-analysis-completed': 'AI专业分析与排查建议已完成',
        'form-ai-troubleshoot-completed': 'AI排查分析与解决方案已完成',
        'form-analysis-failed': '专业分析失败',
        'form-troubleshoot-failed': '排查分析失败',
        'form-analysis-error': '专业分析时出错，请稍后重试',
        'form-troubleshoot-error': '排查分析时出错，请稍后重试',
        'form-edit-fault-title': '编辑故障',
        'form-edit-fault-description': '编辑设备故障记录',
        'form-load-fault-data-failed': '加载故障数据失败',
        'form-load-fault-data-error': '加载故障数据失败，请稍后重试',
        'form-fault-updated-successfully': '故障信息已成功更新！',
        'form-fault-submitted-successfully': '故障报告已成功提交！',
        'form-submit-failed': '提交失败',
        'form-unknown-error': '未知错误',
        'form-submit-error': '提交故障报告时出错，请稍后重试',
        'form-cancel-confirm': '确定要取消吗？未保存的数据将丢失。',
        'form-select-plant': '请选择工厂',
        'form-select-equipment': '请选择设备',
        'form-select-area': '请选择区域',
        'form-select-sub-area': '请选择子区域',
        'form-select-reporter': '请选择报告人',
        'form-load-plant-data-failed': '加载工厂数据失败',
        'form-load-plant-data-error': '加载工厂数据时发生错误',
        'form-load-equipment-data-failed': '加载设备数据失败',
        'form-load-equipment-data-error': '加载设备数据时发生错误',
        'form-load-area-data-failed': '加载区域数据失败',
        'form-load-area-data-error': '加载区域数据时发生错误',
        'form-load-sub-area-data-failed': '加载子区域数据失败',
        'form-load-sub-area-data-error': '加载子区域数据时发生错误',
        'form-load-personnel-data-failed': '加载人员数据失败',
        'form-load-personnel-data-error': '加载人员数据时发生错误',
        
        // Additional keys for AI analysis functionality
        'error-analysis-error': '专业分析时出错，请稍后重试',
        'ai-professional-analysis': 'AI专业分析',
        'error-enter-fault-description': '请先输入故障描述',
        'error-enter-troubleshooting-steps': '请先输入故障排查步骤',
        'ai-analyzing': '分析中...',
        'error-cannot-get-analysis-result': '无法获取分析结果',
        'ai-troubleshooting-analysis-completed': 'AI排查分析与解决方案已完成',
        'error-troubleshooting-analysis-failed': '排查分析失败',
        'error-troubleshooting-analysis-error': '排查分析时出错，请稍后重试',
        'ai-troubleshooting-analysis': 'AI排查分析',
        // Fault List Page
        'fault-list-title': '故障列表',
        'fault-list-description': '查看和管理所有设备故障记录',
        'search-criteria': '搜索条件',
        'search-button': '搜索',
        'reset-button': '重置',
        'load-column-width-error': '加载列宽设置失败',
        'no-matching-faults': '没有找到匹配的故障记录',
        // Fault Detail Page
        'fault-detail-title': '故障详情',
        'fault-detail-description': '查看设备故障的详细信息',
        'basic-info': '基本信息',
        'fault-detail': '故障详情',
        'additional-info': '补充信息',
        'export-document': '导出文档',
        'fault-id': '故障ID',
        'plant': '工厂',
        'fault-equipment': '故障设备',
        'fault-area': '故障区域',
        'fault-subarea': '故障子区域',
        'fault-category': '故障分类',
        'fault-level': '故障等级',
        'report-time': '报告时间',
        'reporter': '报告人',
        'status': '状态',
        'fault-description': '故障描述',
        'troubleshooting': '故障排查',
        'root-cause': '故障根因',
        'resolution': '故障解决',
        'attachments': '附件信息',
        'export-fault-report': '导出故障报告',
        'export-description': '点击下方按钮将完整的故障信息（包括基本信息、故障详情、补充信息和附件）导出为Word文档。',
        'export-word-document': '导出为Word文档',
        'generating-document': '正在生成文档...',
        'back-to-list': '返回列表',
        'edit-fault': '编辑故障',
        'no-fault-id': '未指定故障ID',
        'load-fault-detail-failed': '加载故障详情失败',
        'no-attachments': '暂无附件',
        'equipment-fault-report': '设备故障报告',
        'fault-number': '故障编号',
        'processing-time': '处理时间',
        'resolution-time': '解决时间',
        'image-attachments': '图片附件',
        'other-attachments': '其他附件',
        'image-name': '图片名称',
        'file-size': '文件大小',
        'file-type': '文件类型',
        'image-link': '图片链接',
        'file-name': '文件名称',
        'file-link': '文件链接',
        'image-embed-error': '注意: 图片无法直接嵌入到文档中，请点击上方链接查看图片',
        'no-attachments-report': '此故障报告没有附件',
        'report-generation-info': '报告生成信息',
        'generation-time': '生成时间',
        'generation-method': '生成方式',
        'auto-generated': '系统自动生成',
        'export-failed': '导出失败',
        'high': '高',
        'medium': '中',
        'low': '低',
        'unknown': '未知',
        'pending': '待处理',
        'processing': '处理中',
        'resolved': '已解决',
        'completed': '已完成',
        // Fault Statistics Page
        'fault-statistics-title': '故障统计',
        'fault-statistics-description': '查看设备故障数据分析与趋势',
        'total-faults': '故障总数',
        'in-progress': '处理中',
        'pending': '待处理',
        'urgent-faults': '紧急故障数',
        'fault-distribution': '故障分布',
        'fault-time-trend': '故障时间趋势',
        'fault-type-distribution': '故障类型分布',
        'fault-equipment-distribution': '故障设备分布',
        'fault-area-distribution': '故障区域分布',
        'monthly-statistics': '按月统计',
        'quarterly-statistics': '按季度统计',
        'yearly-statistics': '按年统计',
        'fault-type-chart-placeholder': '故障类型分布图表将显示在这里',
        'fault-trend-chart-placeholder': '故障时间趋势图表将显示在这里',
        'fetch-fault-data-failed': '获取故障数据失败',
        'fault-count': '故障数量',
        'maximum': '最大值',
        'minimum': '最小值'
    },
    en: {
        // Common elements
        'login-title': 'System Login',
        'login-subtitle': 'Please enter your credentials to access the system',
        'username-label': 'Username',
        'password-label': 'Password',
        'login-button': 'Login',
        'guest-text': 'Guest Access',
        'login-error': 'Username or password is incorrect, please try again',
        'page-title': 'Gear Equipment Fault Management',
        'nav-home': 'Home',
        'nav-fault-list': 'Fault List',
        'nav-new-fault': 'New Fault',
        'nav-fault-stats': 'Fault Statistics',
        'nav-info-mgmt': 'Info Management',
        'nav-logout': 'Logout',
        'card-fault-list-title': 'Fault List',
        'card-fault-list-desc': 'View all equipment fault records',
        'card-new-fault-title': 'New Fault',
        'card-new-fault-desc': 'Add new equipment fault record',
        'card-fault-stats-title': 'Fault Statistics',
        'card-fault-stats-desc': 'View equipment fault data analysis',
        'card-info-mgmt-title': 'Info Management',
        'card-info-mgmt-desc': 'Manage equipment and user information',
        'footer-text': 'Website created based on Zhipu AI GLM-4.5 model',
        
        // Fault List Page
        'fault-list-title': 'Fault List',
        'fault-list-subtitle': 'View and manage all equipment fault records',
        'filter-factory': 'Factory Filter',
        'filter-equipment': 'Equipment Filter',
        'filter-status': 'Status Filter',
        'filter-urgency': 'Urgency Filter',
        'filter-apply': 'Apply Filters',
        'filter-reset': 'Reset Filters',
        'table-id': 'ID',
        'table-factory': 'Factory',
        'table-equipment': 'Equipment Name',
        'table-area': 'Area',
        'table-subarea': 'Sub Area',
        'table-fault-type': 'Fault Type',
        'table-fault-desc': 'Fault Description',
        'table-status': 'Status',
        'table-urgency': 'Urgency',
        'table-reporter': 'Reporter',
        'table-report-time': 'Report Time',
        'table-actions': 'Actions',
        'status-pending': 'Pending',
        'status-in-progress': 'In Progress',
        'status-completed': 'Completed',
        'urgency-low': 'Low',
        'urgency-medium': 'Medium',
        'urgency-high': 'High',
        'action-view': 'View',
        'action-edit': 'Edit',
        'action-delete': 'Delete',
        'pagination-previous': 'Previous',
        'pagination-next': 'Next',
        'pagination-info': 'Showing {start}-{end} of {total} records',
        'no-data': 'No data available',
        
        // New Fault Page
        'new-fault-title': 'New Fault',
        'new-fault-subtitle': 'Fill in equipment fault information',
        'form-factory': 'Factory',
        'form-equipment': 'Equipment Name',
        'form-area': 'Area',
        'form-subarea': 'Sub Area',
        'form-fault-type': 'Fault Type',
        'form-fault-desc': 'Fault Description',
        'form-status': 'Status',
        'form-urgency': 'Urgency',
        'form-reporter': 'Reporter',
        'form-report-time': 'Report Time',
        'form-submit': 'Submit',
        'form-reset': 'Reset',
        'form-cancel': 'Cancel',
        'form-save': 'Save',
        'form-loading': 'Saving...',
        'form-success': 'Fault record saved successfully',
        'form-error': 'Save failed, please try again',
        
        // Fault Statistics Page
        'fault-stats-title': 'Fault Statistics',
        'fault-stats-subtitle': 'Equipment fault data analysis',
        'stats-total': 'Total Faults',
        'stats-in-progress': 'In Progress',
        'stats-pending': 'Pending',
        'stats-urgent': 'Urgent Faults',
        'chart-distribution': 'Distribution by Fault Type',
        'chart-trend': 'Fault Time Trend',
        'chart-equipment': 'Distribution by Equipment',
        'chart-area': 'Distribution by Area',
        'filter-month': 'Month',
        'filter-quarter': 'Quarter',
        'filter-year': 'Year',
        'filter-equipment-btn': 'By Equipment',
        'filter-area-btn': 'By Area',
        'chart-fault-type': 'Fault Distribution',
        'chart-max': 'Maximum',
        'chart-min': 'Minimum',
        
        // Info Management Page
        'info-mgmt-title': 'Info Management',
        'info-mgmt-subtitle': 'Manage equipment and user information',
        'tab-equipment': 'Equipment Management',
        'tab-user': 'User Management',
        'basic-data-maintenance': 'Basic Data Maintenance',
        'fault-data-download': 'Fault Data Download',
        'download-description': 'Download fault data table for offline analysis',
        'download-features': 'Features: Includes all fault records, supports Excel format, can be used for offline analysis',
        'download-button': 'Download Fault Data',
        'action-add-single': 'Add Single',
        'action-batch-download': 'Batch Download',
        'action-batch-upload': 'Batch Upload',
        'modal-add-equipment': 'Add Equipment',
        'modal-add-user': 'Add User',
        'modal-plant': 'Factory',
        'modal-equipment-name': 'Equipment Name',
        'modal-area': 'Area',
        'modal-subarea': 'Sub Area',
        'modal-name': 'Name',
        'modal-function': 'Department',
        'modal-commitment': 'Position',
        'modal-save': 'Save',
        'modal-cancel': 'Cancel',
        'modal-loading': 'Saving...',
        'modal-error': 'Save failed: {error}',
        'modal-success-equipment': 'Equipment added successfully!',
        'modal-success-user': 'User added successfully!',
        'modal-update-success-equipment': 'Equipment updated successfully!',
        'modal-update-success-user': 'User updated successfully!',
        'modal-delete-confirm': 'Are you sure you want to delete this record?',
        'modal-delete-loading': 'Deleting...',
        'modal-delete-success': 'Delete successful',
        'modal-delete-error': 'Delete failed, please try again',
        'table-loading': 'Failed to load data',
        'upload-success': 'Upload successful! {message}',
        'upload-error': 'Upload failed: {message}',
        
        // Additional keys for fault-list.html
        'fault-detail-title': 'Fault Detail',
        'fault-id-label': 'Fault ID',
        'description-section': 'Description',
        'get-fault-detail-failed': 'Failed to get fault detail',
        'get-fault-detail-error': 'Error getting fault detail, please try again later',
        'process-fault-title': 'Process Fault',
        'status-label': 'Status',
        'handler-label': 'Handler',
        'handling-description-label': 'Handling Description',
        'resolution-label': 'Fault Resolution',
        'submit-button': 'Submit',
        'cancel-button': 'Cancel',
        'fault-status-updated': 'Fault processing status has been updated',
        'update-failed': 'Update failed',
        'unknown-error': 'Unknown error',
        'update-fault-status-error': 'Error updating fault status, please try again later',
        'process-fault-error': 'Error processing fault, please try again later',
        'delete-fault-confirm': 'Are you sure you want to delete this fault record? This action cannot be undone.',
        'fault-deleted': 'Fault record has been deleted',
        'delete-failed': 'Delete failed',
        'delete-fault-error': 'Error deleting fault, please try again later',
        'level-high': 'High',
        'level-medium': 'Medium',
        'level-low': 'Low',
        'level-urgent': 'Urgent',
        'status-pending': 'Pending',
        'status-processing': 'Processing',
        'status-resolved': 'Resolved',
        'status-completed': 'Completed',
        'unknown-time': 'Unknown time',
        'no-matching-faults': 'No matching fault records found',
        'load-column-width-error': 'Error loading column width',
        
        // New Fault Page (new-fault.html)
        'new-fault-page-title': 'New Fault',
        'new-fault-page-description': 'Add new equipment fault record',
        'form-required': 'Required',
        'form-basic-info': 'Basic Information',
        'form-factory': 'Factory',
        'form-fault-equipment': 'Fault Equipment',
        'form-fault-area': 'Fault Area',
        'form-fault-sub-area': 'Fault Sub Area',
        'form-fault-category': 'Fault Category',
        'form-fault-level': 'Fault Level',
        'form-report-time': 'Report Time',
        'form-reporter': 'Reporter',
        'form-status': 'Status',
        'form-select-status': 'Select Status',
        'form-status-pending': 'Pending',
        'form-status-in-progress': 'In Progress',
        'form-status-resolved': 'Resolved',
        'form-fault-details': 'Fault Details',
        'form-fault-description': 'Fault Description',
        'form-ai-analysis': 'AI Professional Analysis',
        'form-ai-analysis-title': 'AI Professional Analysis and Troubleshooting Suggestions',
        'form-troubleshooting': 'Fault Troubleshooting',
        'form-ai-troubleshoot': 'AI Troubleshooting Analysis',
        'form-ai-troubleshoot-title': 'AI Troubleshooting Analysis and Solutions',
        'form-root-cause': 'Root Cause',
        'form-resolution': 'Fault Resolution',
        'form-additional-info': 'Additional Information',
        'form-file-upload': 'Upload Files',
        'form-file-upload-hint': 'Support uploading multiple files, such as images, documents, etc.',
        'form-submit': 'Submit',
        'form-cancel': 'Cancel',
        'form-analyzing': 'Analyzing...',
        'form-ai-professional-analysis': 'AI Professional Analysis',
        'form-ai-troubleshooting-analysis': 'AI Troubleshooting Analysis',
        'form-please-enter-fault-description': 'Please enter fault description first',
        'form-please-enter-troubleshooting': 'Please enter troubleshooting steps first',
        'form-ai-analysis-completed': 'AI professional analysis and troubleshooting suggestions completed',
        'form-ai-troubleshoot-completed': 'AI troubleshooting analysis and solutions completed',
        'form-analysis-failed': 'Professional analysis failed',
        'form-troubleshoot-failed': 'Troubleshooting analysis failed',
        'form-analysis-error': 'Error during professional analysis, please try again later',
        'form-troubleshoot-error': 'Error during troubleshooting analysis, please try again later',
        'form-edit-fault-title': 'Edit Fault',
        'form-edit-fault-description': 'Edit equipment fault record',
        'form-load-fault-data-failed': 'Failed to load fault data',
        'form-load-fault-data-error': 'Failed to load fault data, please try again later',
        'form-fault-updated-successfully': 'Fault information has been successfully updated!',
        'form-fault-submitted-successfully': 'Fault report has been successfully submitted!',
        'form-submit-failed': 'Submission failed',
        'form-unknown-error': 'Unknown error',
        'form-submit-error': 'Error submitting fault report, please try again later',
        'form-cancel-confirm': 'Are you sure you want to cancel? Unsaved data will be lost.',
        'form-select-plant': 'Please select a factory',
        'form-select-equipment': 'Please select equipment',
        'form-select-area': 'Please select an area',
        'form-select-sub-area': 'Please select a sub area',
        'form-select-reporter': 'Please select a reporter',
        'form-load-plant-data-failed': 'Failed to load factory data',
        'form-load-plant-data-error': 'Error occurred while loading factory data',
        'form-load-equipment-data-failed': 'Failed to load equipment data',
        'form-load-equipment-data-error': 'Error occurred while loading equipment data',
        'form-load-area-data-failed': 'Failed to load area data',
        'form-load-area-data-error': 'Error occurred while loading area data',
        'form-load-sub-area-data-failed': 'Failed to load sub area data',
        'form-load-sub-area-data-error': 'Error occurred while loading sub area data',
        'form-load-personnel-data-failed': 'Failed to load personnel data',
        'form-load-personnel-data-error': 'Error occurred while loading personnel data',
        
        // Additional keys for AI analysis functionality
        'error-analysis-error': 'Error during professional analysis, please try again later',
        'ai-professional-analysis': 'AI Professional Analysis',
        'error-enter-fault-description': 'Please enter fault description first',
        'error-enter-troubleshooting-steps': 'Please enter troubleshooting steps first',
        'ai-analyzing': 'Analyzing...',
        'error-cannot-get-analysis-result': 'Cannot get analysis result',
        'ai-troubleshooting-analysis-completed': 'AI troubleshooting analysis and solutions completed',
        'error-troubleshooting-analysis-failed': 'Troubleshooting analysis failed',
        'error-troubleshooting-analysis-error': 'Error during troubleshooting analysis, please try again later',
        'ai-troubleshooting-analysis': 'AI Troubleshooting Analysis',
        // Fault List Page
        'fault-list-title': 'Fault List',
        'fault-list-description': 'View and manage all equipment fault records',
        'search-criteria': 'Search Criteria',
        'search-button': 'Search',
        'reset-button': 'Reset',
        'load-column-width-error': 'Failed to load column width settings',
        'no-matching-faults': 'No matching fault records found',
        // Fault Detail Page
        'fault-detail-title': 'Fault Detail',
        'fault-detail-description': 'View detailed information of equipment fault',
        'basic-info': 'Basic Information',
        'fault-detail': 'Fault Detail',
        'additional-info': 'Additional Information',
        'export-document': 'Export Document',
        'fault-id': 'Fault ID',
        'plant': 'Factory',
        'fault-equipment': 'Fault Equipment',
        'fault-area': 'Fault Area',
        'fault-subarea': 'Fault Sub Area',
        'fault-category': 'Fault Category',
        'fault-level': 'Fault Level',
        'report-time': 'Report Time',
        'reporter': 'Reporter',
        'status': 'Status',
        'fault-description': 'Fault Description',
        'troubleshooting': 'Fault Troubleshooting',
        'root-cause': 'Root Cause',
        'resolution': 'Fault Resolution',
        'attachments': 'Attachment Information',
        'export-fault-report': 'Export Fault Report',
        'export-description': 'Click the button below to export the complete fault information (including basic information, fault details, additional information and attachments) as a Word document.',
        'export-word-document': 'Export as Word Document',
        'generating-document': 'Generating document...',
        'back-to-list': 'Back to List',
        'edit-fault': 'Edit Fault',
        'no-fault-id': 'No fault ID specified',
        'load-fault-detail-failed': 'Failed to load fault detail',
        'no-attachments': 'No attachments',
        'equipment-fault-report': 'Equipment Fault Report',
        'fault-number': 'Fault Number',
        'processing-time': 'Processing Time',
        'resolution-time': 'Resolution Time',
        'image-attachments': 'Image Attachments',
        'other-attachments': 'Other Attachments',
        'image-name': 'Image Name',
        'file-size': 'File Size',
        'file-type': 'File Type',
        'image-link': 'Image Link',
        'file-name': 'File Name',
        'file-link': 'File Link',
        'image-embed-error': 'Note: Images cannot be directly embedded in the document, please click the link above to view images',
        'no-attachments-report': 'This fault report has no attachments',
        'report-generation-info': 'Report Generation Information',
        'generation-time': 'Generation Time',
        'generation-method': 'Generation Method',
        'auto-generated': 'System Automatically Generated',
        'export-failed': 'Export failed',
        'high': 'High',
        'medium': 'Medium',
        'low': 'Low',
        'unknown': 'Unknown',
        'pending': 'Pending',
        'processing': 'Processing',
        'resolved': 'Resolved',
        'completed': 'Completed',
        // Fault Statistics Page
        'fault-statistics-title': 'Fault Statistics',
        'fault-statistics-description': 'View equipment fault data analysis and trends',
        'total-faults': 'Total Faults',
        'in-progress': 'In Progress',
        'pending': 'Pending',
        'urgent-faults': 'Urgent Faults',
        'fault-distribution': 'Fault Distribution',
        'fault-time-trend': 'Fault Time Trend',
        'fault-type-distribution': 'Fault Type Distribution',
        'fault-equipment-distribution': 'Fault Equipment Distribution',
        'fault-area-distribution': 'Fault Area Distribution',
        'monthly-statistics': 'Monthly Statistics',
        'quarterly-statistics': 'Quarterly Statistics',
        'yearly-statistics': 'Yearly Statistics',
        'fault-type-chart-placeholder': 'Fault type distribution chart will be displayed here',
        'fault-trend-chart-placeholder': 'Fault time trend chart will be displayed here',
        'fetch-fault-data-failed': 'Failed to fetch fault data',
        'fault-count': 'Fault Count',
        'maximum': 'Maximum',
        'minimum': 'Minimum'
    }
};

// Current language
let currentLanguage = 'zh';

// Function to set the language
function setLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('language', lang);
    updatePageLanguage();
}

// Function to update the page language
function updatePageLanguage() {
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            element.textContent = translations[currentLanguage][key];
        }
    });
    
    // Update placeholders
    document.querySelectorAll('[data-lang-placeholder]').forEach(element => {
        const key = element.getAttribute('data-lang-placeholder');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            element.placeholder = translations[currentLanguage][key];
        }
    });
    
    // Update title attributes
    document.querySelectorAll('[data-lang-title]').forEach(element => {
        const key = element.getAttribute('data-lang_title');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            element.title = translations[currentLanguage][key];
        }
    });
}

// Initialize language from localStorage or browser language
function initializeLanguage() {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && translations[savedLanguage]) {
        currentLanguage = savedLanguage;
    } else {
        // Try to detect browser language
        const browserLang = navigator.language.split('-')[0];
        if (translations[browserLang]) {
            currentLanguage = browserLang;
        }
    }
    updatePageLanguage();
}

// Function to get translation text
function getTranslation(key) {
    return translations[currentLanguage][key] || key;
}

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', initializeLanguage);